language: node_js
node_js:
  - 'stable'
script:
  - npm install codecov -g
  - npm run build
  - npm run test
after_success:
  - codecov

# before_deploy:
# cp $TRAVIS_BUILD_DIR/dist/index.js index.js

deploy:
  provider: releases
  skip_cleanup: true
  file: "$TRAVIS_BUILD_DIR/dist/index.js"
  api_key:
    secure: "$API_KEY"
  # on:
    # tags: true
  # jdk: oraclejdk8