name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run  build and test
      run: echo  build and test
    - name: Run a multi-line script
      run: |
         npm i
         npm run build
         npm run test
         
         
  pages:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2
    - name: post pages
      run: echo post pages
    - name: Run a multi-line script
      run: |
         npm i
         npm run build
         npm run pages 
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.3.0
      with:
        build_dir: pages
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



